apiVersion: v1
kind: Secret
metadata:
  name: photo-album-db-secret
  namespace: photo-album
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://demo-photo-album-33d13-postgresql.postgres.database.azure.com:5432/photoalbum?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "photoalbum"
  SPRING_DATASOURCE_PASSWORD: "photoalbum"
