apiVersion: v1
kind: Secret
metadata:
  name: photo-album-db-secret
  namespace: photo-album
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "{{POSTGRES_CONNECTION_STRING}}?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "{{POSTGRES_USER}}"
  SPRING_DATASOURCE_PASSWORD: "{{POSTGRES_PASSWORD}}"